sudo: required 
language: generic 

serices:
 - docker

before_install:
 - docker build -t arjunchandr/docker-react -f Dockerfile.dev . 

script:
 - docker run -e CI=true arjunchandr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-219705519696"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master



