sudo: required 
language: generic 

serices:
 - docker

before_install:
 - docker build -t arjunchandr/docker-react -f Dockerfile.dev . 

script:
 - docker run -e CI=true arjunchandr/docker-react npm run test